# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77b9a4c53c6479482c5f47667f2638a6e25b91a82333f874d2dcb525688eab02759cadd077d1aa142d8b744926a73f7b129a78b9e2a1dac74be749bed401f44e

test:
  secret_key_base: 25f41811b93332245033b046d284ace6379f2a11a193d3f70e8ceb6e84b5afa2772f561dba19649a6c9c48b414a7583594b06494b1f88faec004b403567d69cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
